### ISSUE TITLE
partitioning issues during inference on v3-32

### ISSUE THREAD

**Issue by dptam** [google-research/prompt-tuning#45]
Hi, 

I was running into a partitioning issue on tpus. Also referenced here https://github.com/google-research/t5x/issues/250

## Actual Behavior

I was running inference on prompt-tuning and ran into an issue when doing inference on a v3-32 with the partitioning with `TypeError: 'ShapeDtypeStruct' object is not iterable`. Training works fine on a v3-32, and training and inference work fine on a v3-8.

Here is the traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/eval.py", line 234, in <module>
    gin_utils.run(main)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/gin_utils.py", line 103, in run
    app.run(
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/eval.py", line 213, in main
    _main(argv)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/eval.py", line 231, in _main
    evaluate_using_gin()
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/eval.py", line 127, in evaluate
    train_state_initializer = utils.TrainStateInitializer(
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/utils.py", line 365, in __init__
    self.train_state_axes = partitioner.get_mesh_axes(
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/partitioning.py", line 826, in get_mesh_axes
    mesh_axes_dict = jax.tree_map(flax_partitioning.logical_to_mesh_axes,
  File "/home/dptam/.local/lib/python3.8/site-packages/jax/_src/tree_util.py", line 178, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/dptam/.local/lib/python3.8/site-packages/jax/_src/tree_util.py", line 178, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/dptam/.local/lib/python3.8/site-packages/flax/linen/partitioning.py", line 154, in logical_to_mesh_axes
    axis_name_counts = collections.Counter(array_dim_names)
  File "/usr/lib/python3.8/collections/__init__.py", line 552, in __init__
    self.update(iterable, **kwds)
  File "/usr/lib/python3.8/collections/__init__.py", line 637, in update
    _count_elements(self, iterable)
TypeError: 'ShapeDtypeStruct' object is not iterable
  In call to configurable 'evaluate' (<function evaluate at 0x7f784d161700>)
Rewritten gin arg: --gin_bindings=MIXTURE_OR_TASK_NAME = 'glue_rte_32_shot_32_seed'
Rewritten gin arg: --gin_bindings=MIXTURE_OR_TASK_MODULE = 'prompt_tuning.data.few_glue'
Rewritten gin arg: --gin_bindings=TASK_FEATURE_LENGTHS = {'inputs': 512, 'targets': 8}
Rewritten gin arg: --gin_bindings=CHECKPOINT_PATH = 'gs://nicl/pretrained_models/t5x_checkpoints/t0_3b/checkpoint_1112000'
Rewritten gin arg: --gin_bindings=EVAL_OUTPUT_DIR = 'gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/eval'
Rewritten gin arg: --gin_bindings=utils.DatasetConfig.split = 'validation'
Rewritten gin arg: --gin_bindings=utils.DatasetConfig.batch_size = 128
Rewritten gin arg: --gin_bindings=USE_CACHED_TASKS = False
Rewritten gin arg: --gin_bindings=partitioning.ModelBasedPjitPartitioner.model_parallel_submesh = (4, 4, 1, 2)
Rewritten gin arg: --gin_bindings=PROMPT_FILE = 'gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/numpy_checkpoints/checkpoint_1112300/encoder.prompt.prompt.prompt'
##### Command execution on worker 0 failed with return code 1. Continuing.
##### Command execution on worker 3 failed with return code 1. Continuing.
##### Command execution on worker 1 failed with return code 1. Continuing.
##### Command execution on worker 2 failed with return code 1. Continuing.
```

Adam said there might be a bug in the prompt-tuning configs 

## Steps to Reproduce the Problem

The gin config used: 
```
python3 -m t5x.eval \
  --gin_search_paths="${T5X_DIR},${FLAXFORMER_DIR},${PROMPT_DIR}" \
  --gin_file="prompt_tuning/configs/models/t5_1_1_xl_prompt.gin" \
  --gin_file="prompt_tuning/configs/runs/prompt_eval.gin" \
  --gin.MIXTURE_OR_TASK_NAME="'glue_rte_32_shot_32_seed'" \
  --gin.MIXTURE_OR_TASK_MODULE="'prompt_tuning.data.few_glue'" \
  --gin.TASK_FEATURE_LENGTHS="{'inputs': 512, 'targets': 8}" \
  --gin.CHECKPOINT_PATH="'${PRETRAINED_MODEL}'" \
  --gin.EVAL_OUTPUT_DIR="'${EVAL_DIR}'" \
  --gin.utils.DatasetConfig.split="'validation'" \
  --gin.utils.DatasetConfig.batch_size="128" \
  --gin.USE_CACHED_TASKS="False" \
  --gin.partitioning.ModelBasedPjitPartitioner.model_parallel_submesh="(4, 4, 1, 2)" \
  --gin.PROMPT_FILE="'${PROMPT_FILE}'" \
  --tfds_data_dir=${TFDS_DATA_DIR}
```
## Specifications

tpu v3-32

**Comment by blester125** [comment]
https://github.com/google-research/t5x/pull/256 should fix this. Once that lands (or before if you want to clone the branch and manually install t5x from there) you'll need to reinstall t5x to get the fix and then rerun your eval. If it is still broken after let me know.

**Comment by dptam** [comment]
Yup it works now. Thanks for your quick help!
