### ISSUE TITLE
Issue with multiple vms saving numpy checkpoint 

### ISSUE THREAD

**Issue by dptam** [google-research/prompt-tuning#53]
Hi, 

## Actual Behavior

When training using a v3-32, I get this error where the file already exists for saving checkpoint models. I think it is because each of the 4 TPU vms are trying to save the checkpoint.

```
I0217 01:50:42.143146 140096433429568 utils.py:103] Saving Numpy checkpoints for step 1130000 to gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/numpy_checkpoints/checkpoint_1130000.tmp-1645062642
I0217 01:50:42.143416 140154172939328 utils.py:103] Saving Numpy checkpoints for step 1130000 to gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/numpy_checkpoints/checkpoint_1130000.tmp-1645062642
I0217 01:50:42.143328 140506403216448 utils.py:103] Saving Numpy checkpoints for step 1130000 to gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/numpy_checkpoints/checkpoint_1130000.tmp-1645062642
I0217 01:50:42.143347 139725649984576 utils.py:103] Saving Numpy checkpoints for step 1130000 to gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b/numpy_checkpoints/checkpoint_1130000.tmp-1645062642
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/train.py", line 617, in <module>
    gin_utils.run(main)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/gin_utils.py", line 103, in run
    app.run(
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/train.py", line 596, in main
    _main(argv)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/train.py", line 614, in _main
    train_using_gin()
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/dptam/.local/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/dptam/.local/lib/python3.8/site-packages/t5x/train.py", line 501, in train
    checkpointer.save(trainer.train_state,
  File "/home/dptam/prompt-tuning/prompt_tuning/train/utils.py", line 134, in save
    self.save_numpy(train_state.params, train_state.step)
  File "/home/dptam/prompt-tuning/prompt_tuning/train/utils.py", line 123, in save_numpy
    gfile.rename(tmp_dir, numpy_dir)
  File "/home/dptam/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 620, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists
  In call to configurable 'train' (<function train at 0x7f1306402f70>)
Rewritten gin arg: --gin_bindings=CLASS_LABELS = ['entailment', 'contradiction']
Rewritten gin arg: --gin_bindings=MODEL_DIR = 'gs://nicl/checkpoint_models/rte/32_shot/32_seed/prompt-tuning/t0-3b'
Rewritten gin arg: --gin_bindings=MIXTURE_OR_TASK_NAME = 'glue_rte_32_shot_32_seed'
Rewritten gin arg: --gin_bindings=MIXTURE_OR_TASK_MODULE = 'prompt_tuning.data.few_glue'
Rewritten gin arg: --gin_bindings=TASK_FEATURE_LENGTHS = {'inputs': 512, 'targets': 8}
Rewritten gin arg: --gin_bindings=INITIAL_CHECKPOINT_PATH = 'gs://nicl/pretrained_models/t5x_checkpoints/t0_3b/checkpoint_1112000'
Rewritten gin arg: --gin_bindings=TRAIN_STEPS = 1_212_000
Rewritten gin arg: --gin_bindings=BATCH_SIZE = 32
Rewritten gin arg: --gin_bindings=partitioning.ModelBasedPjitPartitioner.model_parallel_submesh = (4, 4, 1, 2)
Rewritten gin arg: --gin_bindings=USE_CACHED_TASKS = False
```

## Steps to Reproduce the Problem

1.These are the parameters I use: 
```
python3 -m t5x.train \
  --gin_search_paths="${T5X_DIR},${FLAXFORMER_DIR},${PROMPT_DIR}" \
  --gin_file="prompt_tuning/configs/models/t5_1_1_xl_prompt.gin" \
  --gin_file="prompt_tuning/configs/prompts/from_class_labels.gin" \
  --gin_file="prompt_tuning/configs/runs/prompt_finetune.gin" \
  --gin.CLASS_LABELS="['entailment', 'contradiction']" \
  --gin.MODEL_DIR="'${MODEL_DIR}'" \
  --gin.MIXTURE_OR_TASK_NAME="'glue_rte_32_shot_32_seed'" \
  --gin.MIXTURE_OR_TASK_MODULE="'prompt_tuning.data.few_glue'" \
  --gin.TASK_FEATURE_LENGTHS="{'inputs': 512, 'targets': 8}" \
  --gin.INITIAL_CHECKPOINT_PATH="'${PRETRAINED_MODEL}'" \
  --gin.TRAIN_STEPS="1_100_300" \
  --gin.BATCH_SIZE="8" \
  --gin.USE_CACHED_TASKS="False" \
  --tfds_data_dir=${TFDS_DATA_DIR}
```

## Specifications
v3-32

**Comment by dptam** [comment]
Nvm. I think this was an issue on my end.
